---
title: "PULSE_EW-NT-20221019"
author: "Nate Thomas"
date: "2022-10-19"
output: html_document
---

```{r}
library("dplyr")
```

NIOSH WSH (PAR-20-312) Project - Household PULSE Data Analysis
Data: HPS data phase 3.1-3.5 (week 28-48)
Task#1: Essential work settings - counts 06/20/2022 ~
Task#2: Shot by EW 8/22/2022 ~

Table of Contents
1. Read data folders
2. Clean and prepare data
2.1 Merge data and wieghts

# 1. Read Data

```{r}
#initialize empty data list
raw_data <- data.frame()
raw_weights <- data.frame()

#iterate through data folder to pull in each week
for (i in 1:(length(list.dirs('./Data'))-1)){
  dir = list.dirs('./Data')[i+1]
  if ((i+27)<41) {
    raw_data = dplyr::bind_rows(raw_data,read.csv(paste(dir,'/pulse2021_puf_',i+27,'.csv',sep='')))
    print(paste(dir,'/pulse2021_puf_',i+27,'.csv',sep=''))
    raw_weights = dplyr::bind_rows(raw_weights,read.csv(paste(dir,'/pulse2021_repwgt_puf_',i+27,'.csv',sep='')))
  }
  else {
    raw_data = dplyr::bind_rows(raw_data,read.csv(paste(dir,'/pulse2022_puf_',i+27,'.csv',sep='')))
    print(paste(dir,'/pulse2022_puf_',i+27,'.csv',sep=''))
    raw_weights = dplyr::bind_rows(raw_weights,read.csv(paste(dir,'/pulse2022_repwgt_puf_',i+27,'.csv',sep='')))
  }
}

#save.image()
```

# 2. Clean and prepare data

```{r}
#Year 2021 for weeks 28-40, otherwise 2022
df <- raw_data %>% 
  mutate(yr = ifelse(WEEK < 41,2021,2022))
```

## 2.1 Merge data and wieghts

```{r}
df <- df %>%
  inner_join(raw_weights, by = c('SCRAM','WEEK'))
```

## 2.2 Keep only variables needed

```{r}
df <- df %>%
  mutate(`PWEIGHT1-PWEIGHT80` = PWEIGHT1-PWEIGHT80) %>%
  select(## UNIQUE ID ##
         SCRAM,
         ## RESPONSE WEEK ##
         WEEK,
         ## DEMOGRAPHICS ##
         TBIRTH_YEAR,
         EGENDER, #phase 3.1
         EGENID_BIRTH, #phase 3.2+
         RHISPANIC,
         RRACE,
         EEDUC,
         ## DISABILITY ##
         SEEING,
         HEARING,
         REMEMBERING,
         MOBILITY,
         ## EMPLOYMENT ##
         ANYWORK,
         WKVOL,
         SETTING,
         ## VACCINATION ##
         RECVDVACC,
         ## LOCATION ##
         REGION,
         EST_ST,
         ## WEIGHTS ##
         PWEIGHT,
         HWEIGHT,
         `PWEIGHT1-PWEIGHT80`)
```
